In [2]:
import numpy as np
print(np.__version__)

2.4.4


In [2]:
import numpy as np

b = np.array([10,20,30])
print(b)

[10 20 30]


In [3]:
c = np.zeros(3)
d = np.ones(5)
e = np.arange(0, 11)

print(c)
print(d)
print(e)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
f = np.array([[1, 2, 3, 3], [4, 5, 6, 6]])
print(f)

[[1 2 3 3]
 [4 5 6 6]]


In [7]:
a = [1, 2, 3, 51]           #List
b = np.array([1, 2, 3, 51]) #numpy array

print(a)
print(b)

[1, 2, 3, 51]
[ 1  2  3 51]


In [ ]:
#two dimensional array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
# Multi dimension array

arr = np.array([1, 2, 3], ndmin = 5)
print(arr)

print(arr.ndim)

[[[[[1 2 3]]]]]
5


In [18]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6, 7])

print(arr1 + arr2)
print(arr1 * arr2)
print(arr1[1:3])
print(np.sum(arr1))


new_arr1 = arr1.reshape(2,2)
print(new_arr1)

[ 5  7  9 11]
[ 4 10 18 28]
[2 3]
10
[[1 2]
 [3 4]]
