In [2]:
import numpy as np
print(np.__version__)

2.4.4


In [1]:
import numpy as np

b = np.array([10,20,30])
print(b)

[10 20 30]


In [5]:
c = np.zeros(3)
d = np.ones(5)
e = np.arange(0, 11)

print(c)
print(d)
print(e)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
f = np.array([[1, 2, 3, 3], [4, 5, 6, 6]])
print(f)

[[1 2 3 3]
 [4 5 6 6]]
